osx_image: xcode11.4
language: objective-c
branches:
  only:
    - master
podfile: Example/Podfile 
before_install:
  - brew update
  - gem install cocoapods
  - gem install xcpretty -N
  - brew install swiftlint || true
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/RSRealmHelper.xcworkspace -scheme RSRealmHelper-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,OS:13.4.1,name:iPhone 11 Pro Max' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
